version: '3'
services:

  jupyter:
    build: jupyter/docker/.
#    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    user: jovyan
    volumes:
      - ${PWD}/jupyter/work:/home/jovyan/work
      - ${PWD}/jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
    restart: unless-stopped

networks:
  default:
